channels:
  - conda-forge
  - defaults

dependencies:
  - flann=1.9.1
  - pdal=2.6.0 
  - ale>=0.9.1, <1
  - armadillo
  - boost>=1.72.0, <2
  - boost-cpp>=1.72.0, <2
  - blas
  - usgs-astrogeology::bullet
  - bz2file
  - bzip2
  - cmake >=3.15, <4
  - cspice=67
  - csm>=3.0.3,<3.0.4
  - curl>=8.3.0,<9.0a0
  - cxx-compiler>=1.1.2
  - doxygen
  - eigen>=3, <4
  - embree>=3, <4
  - ffmpeg
  - geos>=3.12.1, <4
  - geotiff
  - gmp
  - graphviz
  - gsl>=2.6
  - hdf5>=1.14.2,<1.14.3.0a0
  - icu
  - inja
  - jama
  - usgs-astrogeology::kakadu==1
  - kalasiris
  - krb5
  - libboost>=1.72.0, <2
  - libgdal >=3.7.2,<3.8.0a0
  - libopencv>=4.5.2, <5
  - libpng>=1.6.34, <2
  - libprotobuf
  - libtiff>=4.0, <5
  - libxml2
  - make
  - mesalib
  - mysql
  - mysql-connector-c
  - nanoflann<1.4
  - nlohmann_json
  - ninja>=1.7.2, <2
  - nn
  - opencv>=4.5.2, <5
  - openssl>=3.1.2,<4.0a0
  - pcl=1.13.1=h86d90ae_2
  - plio
  - protobuf
  - python=3.12
  - python_abi=3.12
  - pytest
  - qhull
  - qt-main
  - qwt
  - rclone
  - sqlite>=3.43.0,<4.0a0
  - suitesparse
  - superlu
  - swig
  - texlive-core
  - tnt
  - x264
  - xalan-c
  - xerces-c>=3.2.4,<3.3.0a0
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib>=1.2.13,<1.3.0a0
