name: ssh
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    # No caching of dependencies, as the cache does not change when it is
    # modified, and it can expire. See build_test.sh how to fetch an
    # offline tarball with dependencies, and how to update that one if need
    # be.
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3 # disconnects after about 40 minutes
      #uses: owenthereal/action-upterm@v1 # disconnects after 30 minutes
      timeout-minutes: 600
      with:
        limit-access-to-actor: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
         # Useful for saving any results produced in this session. Can be later
         # downloaded.
         name: ssh-test-${{ runner.os }}
         path: ~/work/StereoPipeline/packages
         retention-days: 2
      continue-on-error: true
