name: ssh_mac_x64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel
    steps:
    
    # Fetch miniconda
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: ""
    
    # Fetch the code
    - uses: actions/checkout@v3

    # Set up ssh for interactive use
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3 # disconnects after about 40 minutes
      timeout-minutes: 600
      with:
        limit-access-to-actor: true

    # Upload the artifacts that were saved in the directory below before exiting
    # the ssh session. Useful for saving any results produced in this session.
    # Can be later downloaded manually and saved to a permanent location.
    # See save_mac_deps.sh for how to prepare the dependencies for upload.
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with: 
         name: ASP-dependencies-${{ runner.os }}
         path: ~/work/StereoPipeline/packages
         retention-days: 2
      continue-on-error: true
